#!/usr/bin/env bash
set -euo pipefail

DEVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR_DIR="${1:-${ANDROID_BUILD_TOP:-$(cd "$DEVICE_DIR/../../.." && pwd)}/vendor/onyx/leaf3}"
BLOBS="$VENDOR_DIR/proprietary/vendor"
OUT="$VENDOR_DIR/leaf3-vendor.mk"

[[ -d "$BLOBS" ]] || { echo "Missing extracted blobs: $BLOBS" >&2; exit 1; }
mkdir -p "$VENDOR_DIR"

{
  echo 'LOCAL_PATH := vendor/onyx/leaf3'
  echo
  printf '%s\n' 'PRODUCT_COPY_FILES += \'
  find "$BLOBS" \( -type f -o -type l \) -print | LC_ALL=C sort | while IFS= read -r source; do
    relative="${source#"$VENDOR_DIR/proprietary/"}"
    # These outputs are generated by the platform build and cannot be copied.
    # Vendor Java apps need dedicated prebuilt modules; they are intentionally
    # excluded during native-hardware first boot bring-up.
    case "$relative" in
      vendor/build.prop|vendor/default.prop|vendor/etc/fstab.qcom|vendor/etc/fs_config_dirs|vendor/etc/fs_config_files|vendor/etc/group|vendor/etc/passwd|vendor/etc/vintf/*|*.apk|*.jar|*.odex|*.vdex) continue;;
      vendor/etc/init/android.hardware.*|vendor/etc/init/boringssl_self_test.rc) continue;;
      # Lineage supplies Android-namespaced HAL services, including several
      # Qualcomm implementations such as the USB HAL. Keep only vendor-
      # namespaced stock HAL services (vendor.qti.*, etc.).
      vendor/bin/hw/android.hardware.*) continue;;
      # Keep other HAL executables below vendor/bin/hw. Direct vendor/bin
      # entries mix Qualcomm daemons with platform utilities (awk, applypatch,
      # etc.); copying the latter over Lineage build targets is invalid.
      vendor/bin/*/*) :;;
      vendor/bin/*) continue;;
    esac
    printf '    $(LOCAL_PATH)/proprietary/%s:$(TARGET_COPY_OUT_VENDOR)/%s \\\n' "${relative#vendor/}" "${relative#vendor/}"
  done
  echo
  # VINTF XML is assembled by the build system, rather than copied as a raw
  # vendor file.  The stock Android 11 declarations match the stock HALs.
  if [[ -f "$BLOBS/etc/vintf/manifest.xml" ]]; then
    echo 'DEVICE_MANIFEST_FILE += $(LOCAL_PATH)/proprietary/vendor/etc/vintf/manifest.xml'
  fi
  if [[ -f "$BLOBS/etc/vintf/compatibility_matrix.xml" ]]; then
    echo 'DEVICE_MATRIX_FILE += $(LOCAL_PATH)/proprietary/vendor/etc/vintf/compatibility_matrix.xml'
  fi
} > "$OUT"
