#!/usr/bin/env bash
set -euo pipefail

DEVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR_DIR="${1:-${ANDROID_BUILD_TOP:-$(cd "$DEVICE_DIR/../../.." && pwd)}/vendor/onyx/leaf3}"
BLOBS="$VENDOR_DIR/proprietary/vendor"
OUT="$VENDOR_DIR/leaf3-vendor.mk"

[[ -d "$BLOBS" ]] || { echo "Missing extracted blobs: $BLOBS" >&2; exit 1; }
mkdir -p "$VENDOR_DIR"

{
  echo 'LOCAL_PATH := vendor/onyx/leaf3'
  echo
  printf '%s\n' 'PRODUCT_COPY_FILES += \'
  find "$BLOBS" \( -type f -o -type l \) -print | LC_ALL=C sort | while IFS= read -r source; do
    relative="${source#"$VENDOR_DIR/proprietary/"}"
    # These outputs are generated by the platform build and cannot be copied.
    # Vendor Java apps need dedicated prebuilt modules; they are intentionally
    # excluded during native-hardware first boot bring-up.
    case "$relative" in
      vendor/build.prop|vendor/default.prop|vendor/etc/fstab.qcom|*.apk|*.jar|*.odex|*.vdex) continue;;
    esac
    printf '    $(LOCAL_PATH)/proprietary/%s:$(TARGET_COPY_OUT_VENDOR)/%s \\\n' "${relative#vendor/}" "${relative#vendor/}"
  done
  echo
} > "$OUT"
