#!/usr/bin/env bash
set -euo pipefail

DEVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR_DIR="${1:-${ANDROID_BUILD_TOP:-$(cd "$DEVICE_DIR/../../.." && pwd)}/vendor/onyx/leaf3}"
BLOBS="$VENDOR_DIR/proprietary/vendor"
OUT="$VENDOR_DIR/leaf3-vendor.mk"

[[ -d "$BLOBS" ]] || { echo "Missing extracted blobs: $BLOBS" >&2; exit 1; }
mkdir -p "$VENDOR_DIR"

# A stock vendor partition is not a proprietary-files list: it also contains
# Android files generated by the target build. Select only device-specific
# runtime inputs for the initial bring-up. Add further files only when a boot
# log demonstrates that a specific Qualcomm/ONYX component needs them.
is_selected_blob() {
  case "$1" in
    # Android-namespaced HAL services are built by Lineage, even when their
    # stock executable name has a Qualcomm suffix.
    vendor/bin/hw/android.hardware.*|vendor/lib*/hw/android.hardware.*)
      return 1;;
    # Qualcomm/ONYX services, their hardware modules, and GPU modules.
    vendor/bin/hw/vendor.*|vendor/bin/hw/*qti*|vendor/lib*/hw/vendor.*|vendor/lib*/hw/*qti*|vendor/lib*/egl/*|vendor/lib*/soundfx/*)
      return 0;;
    vendor/lib*/hw/*)
      return 0;;

    # Firmware is always device-specific.
    vendor/firmware/*|vendor/firmware_mnt/*|vendor/dsp/*|vendor/lib*/firmware/*)
      return 0;;

    # Keep non-platform vendor shared libraries. The exclusions are runtime
    # libraries built by Lineage itself and must never be copied from stock.
    vendor/lib/*.so|vendor/lib64/*.so)
      case "${1##*/}" in
        android.hardware.*|android.hidl.*|libandroid*|libbase.so|libbinder*|libc++.so|libc.so|libcutils.so|libdl.so|libEGL.so|libGLES*|libhardware*.so|libhidl*.so|liblog.so|libm.so|libnativewindow.so|libprocessgroup.so|libselinux.so|libstdc++.so|libutils.so|libvndksupport.so|libvulkan.so|libz.so)
          return 1;;
        *) return 0;;
      esac;;

    # Hardware configuration consumed by vendor services. Do not include
    # generic account, linker, init, VINTF, or shell configuration files.
    vendor/etc/audio*|vendor/etc/bluetooth/*|vendor/etc/camera/*|vendor/etc/data/*|vendor/etc/display/*|vendor/etc/firmware/*|vendor/etc/gps*|vendor/etc/media*|vendor/etc/permissions/*|vendor/etc/seccomp_policy/*|vendor/etc/sensors/*|vendor/etc/thermal*|vendor/etc/wifi/*|vendor/etc/wlan/*)
      return 0;;
    vendor/etc/init/init.qcom.*|vendor/etc/init/init.qti.*|vendor/etc/init/init.onyx.*|vendor/etc/init/vendor.qti.*|vendor/etc/init/vendor.onyx.*)
      return 0;;
  esac
  return 1
}

{
  echo 'LOCAL_PATH := vendor/onyx/leaf3'
  echo
  printf '%s\n' 'PRODUCT_COPY_FILES += \'
  find "$BLOBS" \( -type f -o -type l \) -print | LC_ALL=C sort | while IFS= read -r source; do
    relative="${source#"$VENDOR_DIR/proprietary/"}"
    is_selected_blob "$relative" || continue
    printf '    $(LOCAL_PATH)/proprietary/%s:$(TARGET_COPY_OUT_VENDOR)/%s \\\n' "${relative#vendor/}" "${relative#vendor/}"
  done
  echo
  # VINTF XML is assembled by the build system, rather than copied as a raw
  # vendor file.  The stock Android 11 declarations match the stock HALs.
  if [[ -f "$BLOBS/etc/vintf/manifest.xml" ]]; then
    echo 'DEVICE_MANIFEST_FILE += $(LOCAL_PATH)/proprietary/vendor/etc/vintf/manifest.xml'
  fi
  if [[ -f "$BLOBS/etc/vintf/compatibility_matrix.xml" ]]; then
    echo 'DEVICE_MATRIX_FILE += $(LOCAL_PATH)/proprietary/vendor/etc/vintf/compatibility_matrix.xml'
  fi
} > "$OUT"
